CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "Requests" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "CategoryId" integer NOT NULL,
    "State" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RequesterId" text NOT NULL,
    "AssigneeId" text,
    CONSTRAINT "PK_Requests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Requests_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Comments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RequestId" integer NOT NULL,
    "Text" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text NOT NULL,
    "IsInternal" boolean NOT NULL,
    CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comments_Requests_RequestId" FOREIGN KEY ("RequestId") REFERENCES "Requests" ("Id") ON DELETE CASCADE
);

CREATE TABLE "StatusHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RequestId" integer NOT NULL,
    "PreviousState" integer NOT NULL,
    "NewState" integer NOT NULL,
    "ChangedAt" timestamp with time zone NOT NULL,
    "ChangedBy" text NOT NULL,
    "Reason" text,
    CONSTRAINT "PK_StatusHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StatusHistories_Requests_RequestId" FOREIGN KEY ("RequestId") REFERENCES "Requests" ("Id") ON DELETE CASCADE
);

INSERT INTO "Categories" ("Id", "Description", "Name")
VALUES (1, 'Roads, bridges, etc.', 'Infrastructure');
INSERT INTO "Categories" ("Id", "Description", "Name")
VALUES (2, 'Water, electricity, etc.', 'Utilities');
INSERT INTO "Categories" ("Id", "Description", "Name")
VALUES (3, 'Public parks and recreation', 'Parks');

CREATE INDEX "IX_Comments_RequestId" ON "Comments" ("RequestId");

CREATE INDEX "IX_Requests_CategoryId" ON "Requests" ("CategoryId");

CREATE INDEX "IX_StatusHistories_RequestId" ON "StatusHistories" ("RequestId");

SELECT setval(
    pg_get_serial_sequence('"Categories"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Categories") + 1,
        nextval(pg_get_serial_sequence('"Categories"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260930160638_InitialCreate', '10.0.12');

COMMIT;

